### ISSUE TITLE
How do i apply the long distant patch.

### ISSUE THREAD

**Issue by CuteistCat** [mineLdiver/OptiBabric#11]

**Comment by mineLdiver** [comment]
Apply it to the OptiFine's zip

**Comment by CuteistCat** [comment]
how is it applyed to the zip?

**Comment by mineLdiver** [comment]
> how is it applyed to the zip?

Just copy over the .class file(s)

**Comment by CuteistCat** [comment]
ok thats what i was thinking

**Comment by CuteistCat** [comment]
BTW do you have a copy of the HD MT G2 patch as it says not avalible

**Comment by CuteistCat** [comment]
found one
