### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by aaaapai** [mineLdiver/OptiBabric#6]
I only installed Optibabric, beta _ OptiFine _ 1.7.3 _ HD _ AA _ G5.zip 
 But when I started it, it crashed.
[latest.log](https://github.com/mineLdiver/OptiBabric/files/12318815/latest.log)

**Comment by mineLdiver** [comment]
This is the same crash that occurs with StationAPI. So I'd bet this is neither StationAPI nor OptiBabric doing this.

Either contact Babric, or Pojav devs.
